<?php
/* THIS IS A GENERATED FILE. DO NOT EDIT DIRECTLY. */
$sg_security = array(
__( "Could not connect to the WordPress REST API. Either a security plugin, custom function or rules in your .htaccess file is preventing the WordPress REST API from working properly. SG Security is using it to store its options and other functionalities so please make sure it works properly.", 'sg-security' ),
__( "Invalid format.", 'sg-security' ),
__( "You can't enable Away Mode for every day of the week.", 'sg-security' ),
__( "This field is required.", 'sg-security' ),
__( "Username ‘admin’ is not allowed.", 'sg-security' ),
__( "This field is required.", 'sg-security' ),
__( "Success", 'sg-security' ),
__( "Error", 'sg-security' ),
__( "Cancel", 'sg-security' ),
__( "Confirm", 'sg-security' ),
__( "Unknown Visitors Activity", 'sg-security' ),
__( "Registered Users Activity", 'sg-security' ),
__( "Blocked", 'sg-security' ),
__( "Filter Activity", 'sg-security' ),
__( "close", 'sg-security' ),
__( "reset", 'sg-security' ),
__( "Blocked On", 'sg-security' ),
__( "User/Ip", 'sg-security' ),
__( "Actions", 'sg-security' ),
__( "unblock", 'sg-security' ),
__( "Timestamp", 'sg-security' ),
__( "User", 'sg-security' ),
__( "IP Address", 'sg-security' ),
__( "Hostname:", 'sg-security' ),
__( "Activity", 'sg-security' ),
__( "Actions", 'sg-security' ),
__( "Manage User Traffic", 'sg-security' ),
__( "View Activity", 'sg-security' ),
__( "Timestamp", 'sg-security' ),
__( "Visitor Type", 'sg-security' ),
__( "IP Address", 'sg-security' ),
__( "Hostname:", 'sg-security' ),
__( "Page Visited", 'sg-security' ),
__( "Response", 'sg-security' ),
__( "Actions", 'sg-security' ),
__( "Manage IP Traffic", 'sg-security' ),
__( "View Activity", 'sg-security' ),
__( "Login Settings", 'sg-security' ),
__( "Login Access", 'sg-security' ),
__( "Currently your WordPress login can be accessed by any IP. You can limit the access to specific IPs or range of IPs in order to prevent brute-force attacks or malicious login attempts.", 'sg-security' ),
__( "configure", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Two-factor Authentication for Admin & Editors Users", 'sg-security' ),
__( "Two-factor authentication forces admin users to login only after providing a token, generated from the Google Authenticator application. When you enable this option, <strong>all admin & editor users will be asked to configure their two-factor authentication in the Authenticator app on their next login.</strong>", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Disable the “admin” Username", 'sg-security' ),
__( "This option will disable the usage of “admin” as a username. If there’s an existing user called “admin”, you will be asked to provide a new username.", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Limit Login Attempts", 'sg-security' ),
__( "Limit the number of times a given user can attempt to log in to your wp-admin with incorrect credentials. Once the login attempt limit is reached, the IP from which the attempts have originated will be blocked first for 1 hour. If the attempts continue after the first hour, the limit will then be triggered for 24 hours and then for 7 days.", 'sg-security' ),
__( "Post-hack Actions", 'sg-security' ),
__( "Reinstall All Free Plugins", 'sg-security' ),
__( "Doing this will reinstall the same version of all free plugins you have installed in order to make sure that their codebase is not compromised by an attacker.", 'sg-security' ),
__( "reinstall all", 'sg-security' ),
__( "Force Password Reset", 'sg-security' ),
__( "All users will be required to change their passwords upon their next login. <strong>All currently logged in users will be instantly logged out.</strong>", 'sg-security' ),
__( "force password reset", 'sg-security' ),
__( "Log out All Users", 'sg-security' ),
__( "This will log out all currently logged in users without asking them to change their passwords.", 'sg-security' ),
__( "Log out All Users", 'sg-security' ),
__( "Site Security", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Lock and Protect System Folders", 'sg-security' ),
__( "By enabling this option you are ensuring that no unauthorised or malicious scripts can be executed in your system folders. This is an often exploited back door you can close with a simple toggle.", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Hide WordPress Version", 'sg-security' ),
__( "Many attackers scan sites for vulnerable WordPress versions. By hiding the version from your site HTML, you avoid being marked by hackers for mass attacks.", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Disable Themes & Plugins Editor", 'sg-security' ),
__( "Disable the option to edit themes and plugins code directly from the WordPress admin to prevent potential coding errors or unauthorised access via the WordPress editor.", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Disable XML-RPC", 'sg-security' ),
__( "XML-RPC was designed as a protocol enabling WordPress to communicate with third-party systems but recently it has been used in a number of exploits. Unless you specifically need to use it, we recommend that XML-RPC is always disabled.", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Disable RSS and ATOM Feeds", 'sg-security' ),
__( "RSS and ATOM feeds are often used to scrape your content and to perform a number of attacks against your site. Only use feeds if you have readers using your site via RSS readers.", 'sg-security' ),
__( "recommended", 'sg-security' ),
__( "Advanced XSS Protection", 'sg-security' ),
__( "Enabling this option will add extra headers to your site for protection against XSS attacks.", 'sg-security' ),
__( "Delete the Default Readme.html", 'sg-security' ),
__( "WordPress comes with a Readme.html file containing information about your website. The Readme.txt is often used by hackers to compile lists of potentially vulnerable sites which can be hacked or attacked.", 'sg-security' ),
__( "delete", 'sg-security' ),
__( "Unblock <em><strong>", 'sg-security' ),
__( "Block <em><strong>", 'sg-security' ),
__( "<strong>", 'sg-security' ),
__( "Blocking <strong>", 'sg-security' ),
__( "Are you sure you wish to proceed?", 'sg-security' ),
__( "Unblock <em><strong>", 'sg-security' ),
__( "Block <em><strong>", 'sg-security' ),
__( "<strong>", 'sg-security' ),
__( "Blocking <strong>", 'sg-security' ),
__( "Are you sure you wish to proceed?", 'sg-security' ),
__( "Recent Activity", 'sg-security' ),
__( "View all logs", 'sg-security' ),
__( "Security Hardening", 'sg-security' ),
__( "Important Notifications", 'sg-security' ),
__( "Specific Period", 'sg-security' ),
__( "Weekly", 'sg-security' ),
__( "Daily", 'sg-security' ),
__( "Monday", 'sg-security' ),
__( "Tuesday", 'sg-security' ),
__( "Wednesday", 'sg-security' ),
__( "Thursday", 'sg-security' ),
__( "Friday", 'sg-security' ),
__( "Saturday", 'sg-security' ),
__( "Sunday", 'sg-security' ),
__( "Configure Away Mode", 'sg-security' ),
__( "Use Away Mode with caution.", 'sg-security' ),
__( "When Away Mode is enabled, you won’t be able to access your website and make changes, including disabling the away mode.", 'sg-security' ),
__( "Mode", 'sg-security' ),
__( "From", 'sg-security' ),
__( "To", 'sg-security' ),
__( "From", 'sg-security' ),
__( "To", 'sg-security' ),
__( "You can enable Away Mode for maximum of 23 hours daily.", 'sg-security' ),
__( "Configure Login URL", 'sg-security' ),
__( "Change the “admin” username", 'sg-security' ),
__( "A username “admin” already exists. Please provide a new username for this user.", 'sg-security' ),
__( "New username:", 'sg-security' ),
__( "Bear in mind that the user will NOT be notified of the change.", 'sg-security' ),
__( "IP", 'sg-security' ),
__( "Manage Login Access", 'sg-security' ),
);
/* THIS IS THE END OF THE GENERATED FILE */