<?php

// Flat icons
function ecademy_flaticons() {
    return [
        'flaticon-search'               => esc_html__('Search', 'ecademy'),
        'flaticon-shopping-cart'        => esc_html__('Cart', 'ecademy'),
        'flaticon-arrow'                => esc_html__('Arrow', 'ecademy'),
        'flaticon-people'               => esc_html__('People', 'ecademy'),
        'flaticon-agenda'               => esc_html__('Agenda', 'ecademy'),
        'flaticon-brain-process'        => esc_html__('Brain Process', 'ecademy'),
        'flaticon-computer'             => esc_html__('Computer', 'ecademy'),
        'flaticon-world'                => esc_html__('World', 'ecademy'),
        'flaticon-shield-1'             => esc_html__('Shield', 'ecademy'),
        'flaticon-search-1'             => esc_html__('Search Two', 'ecademy'),
        'flaticon-time-left'            => esc_html__('Time Left', 'ecademy'),
        'flaticon-quotation'            => esc_html__('Quotation', 'ecademy'),
        'flaticon-play'                 => esc_html__('Play', 'ecademy'),
        'flaticon-user'                 => esc_html__('User', 'ecademy'),
        'flaticon-calendar'             => esc_html__('Calender', 'ecademy'),
        'flaticon-heart'                => esc_html__('Heart', 'ecademy'),
        'flaticon-right-chevron'        => esc_html__('Right Chevron', 'ecademy'),
        'flaticon-tag'                  => esc_html__('Tag', 'ecademy'),
        'flaticon-teacher'              => esc_html__('Teacher', 'ecademy'),
        'flaticon-time3"'               => esc_html__('Time 3', 'ecademy'),
        'flaticon-distance-learning'    => esc_html__('Distance Learning', 'ecademy'),
        'flaticon-web'                  => esc_html__('Web', 'ecademy'),
        'flaticon-lock'                 => esc_html__('Lock', 'ecademy'),
        'flaticon-credit-card'          => esc_html__('Credit Card', 'ecademy'),
        'flaticon-share'                => esc_html__('Share', 'ecademy'),
        'flaticon-password'             => esc_html__('Password', 'ecademy'),
        'flaticon-right'                => esc_html__('Right', 'ecademy'),
        'flaticon-history'              => esc_html__('History', 'ecademy'),
        'flaticon-home'                 => esc_html__('Home', 'ecademy'),
        'flaticon-chevron'              => esc_html__('Chevron', 'ecademy'),
        'flaticon-right-arrow'          => esc_html__('Right Arrow', 'ecademy'),
        'flaticon-tick'                 => esc_html__('Tick', 'ecademy'),
        'flaticon-html'                 => esc_html__('HTML', 'ecademy'),
        'flaticon-caption'              => esc_html__('Caption', 'ecademy'),
        'flaticon-quiz'                 => esc_html__('Quiz', 'ecademy'),
        'flaticon-certification3'       => esc_html__('Certification 1', 'ecademy'),
        'flaticon-experience'           => esc_html__('Experience', 'ecademy'),
        'flaticon-tutorials'            => esc_html__('Tutorials', 'ecademy'),
        'flaticon-self-growth'          => esc_html__('Self Growth', 'ecademy'),
        'flaticon-checkmark'            => esc_html__('Checkmark', 'ecademy'),
        'flaticon-webinar'              => esc_html__('Webinar', 'ecademy'),
        'flaticon-redit-card-1'         => esc_html__('Redit Card 1', 'ecademy'),
        'flaticon-verify'               => esc_html__('Verify', 'ecademy'),
        'flaticon-cancel'               => esc_html__('Cancel', 'ecademy'),
        'flaticon-agenda'               => esc_html__('Agenda', 'ecademy'),
        'flaticon-diet'                 => esc_html__('Diet', 'ecademy'),
        'flaticon-vitamin-c'            => esc_html__('Vitamin C', 'ecademy'),
        'flaticon-heart-rate-monitor'   => esc_html__('Heart Rate Monitor', 'ecademy'),
        'flaticon-pineapple'            => esc_html__('Pineapple', 'ecademy'),
        'flaticon-healthy-food'         => esc_html__('Healthy Food', 'ecademy'),
        'flaticon-yoga'                 => esc_html__('Yoga', 'ecademy'),
        'flaticon-lotus'                => esc_html__('Lotus', 'ecademy'),
        'flaticon-tomato'               => esc_html__('Tomato', 'ecademy'),
        'flaticon-yoga-1'               => esc_html__('Yoga 1', 'ecademy'),
        'flaticon-yoga-2'               => esc_html__('Yoga 2', 'ecademy'),
        'flaticon-strawberry'           => esc_html__('Strawberry', 'ecademy'),
        'flaticon-guitar'               => esc_html__('Guitar', 'ecademy'),
        'flaticon-certification-1'      => esc_html__('Certification 2', 'ecademy'),
        'flaticon-artist'               => esc_html__('Artist', 'ecademy'),
        'flaticon-translation'          => esc_html__('Translation', 'ecademy'),
        
        // Box Icons
        'bx bx-info-circle'         => esc_html__( 'Info Circle', 'ecademy-toolkit' ),
        'bx bx-book-open'           => esc_html__( 'Book Open', 'ecademy-toolkit' ),
        'bx bx-shopping-bag'        => esc_html__( 'Shopping', 'ecademy-toolkit' ),
        'bx bxs-badge-dollar'       => esc_html__( 'Dollar', 'ecademy-toolkit' ),
        'bx bx-code-alt'            => esc_html__( 'Code', 'ecademy-toolkit' ),
        'bx bx-flag'                => esc_html__( 'Flag', 'ecademy-toolkit' ),
        'bx bx-camera'              => esc_html__( 'Camera', 'ecademy-toolkit' ),
        'bx bx-layer'               => esc_html__( 'Layer', 'ecademy-toolkit' ),
        'bx bxs-flag-checkered'     => esc_html__( 'Flag Checkered', 'ecademy-toolkit' ),
        'bx bx-health'              => esc_html__( 'Star', 'ecademy-toolkit' ),
        'bx bx-line-chart'          => esc_html__( 'LLine Chart', 'ecademy-toolkit' ),
        'bx bx-book-reader'         => esc_html__( 'Book Reader', 'ecademy-toolkit' ),
        'bx bx-target-lock'         => esc_html__( 'Target Lock', 'ecademy-toolkit' ),
        'bx bxs-thermometer'        => esc_html__( 'Thermometer', 'ecademy-toolkit' ),
        'bx bx-shape-triangle'      => esc_html__( 'Triangle', 'ecademy-toolkit' ),
        'bx bx-font-family'         => esc_html__( 'Font Family', 'ecademy-toolkit' ),
        'bx bxs-drink'              => esc_html__( 'Drink', 'ecademy-toolkit' ),
        'bx bx-first-aid'           => esc_html__( 'First Aid', 'ecademy-toolkit' ),
        'bx bx-bar-chart-alt-2'     => esc_html__( 'Chart', 'ecademy-toolkit' ),
        'bx bx-briefcase-alt-2'     => esc_html__( 'Briefcase', 'ecademy-toolkit' ),
        'bx bx-book-reader'         => esc_html__( 'Book Reader', 'ecademy-toolkit' ),
        'bx bx-target-lock'         => esc_html__( 'Target Lock', 'ecademy-toolkit' ),
    ];
}

function ecademy_include_flaticons() {
    return array_keys(ecademy_flaticons());
}